BaseUrl: "https://arseniyshestakov.com/"
LanguageCode: "en-us"
Title: "Personal website"
Theme: "ghostwriter"
Copyright: "Arseniy Shestakov"
googleAnalytics: "UA-71686871-1"
disqusShortname: "arseniyshestakov"

Author:
  name: "Arseniy Shestakov"

Params:
  intro: true
  headline: "Arseniy Shestakov"
  description: "I am a software engineer, gamer, traveller and Linux enthusiast"
  photo: "/photo.jpg"
#  gplus: "https://google.com/+XXX"
  github: "https://github.com/ArseniyShestakov"
#  gitlab: "https://gitlab.com/ArseniyShestakov"
  linkedin: "https://linkedin.com/in/arseniyshestakov/"
  twitter: "https://twitter.com/arsenyshestakov"
#  stackoverflow: "https://stackoverflow.com/users/4207535/arseniy-shestakov"
  email: "me@arseniyshestakov.com"
  phone: "+447393026466"
  opengraph: true
  shareTwitter: true
  shareFacebook: true
  shareGooglePlus: true
  shareLinkedIn: true
  dateFormat: "Mon, Jan 2, 2006"
  highlightJsUrl: ""
  highlightJsLocalUrl: ""
# All kind of stuff for the footer
  facebook: "https://www.facebook.com/ArseniyShestakov"
  vkontakte: "https://vk.com/arseniyshestakov"
  instagram: "https://www.instagram.com/arseniyshestakov/"
  goodreads: "https://www.goodreads.com/ArseniyShestakov"
  steam: "https://steamcommunity.com/id/arseniyshestakov/"
  twitch: "https://www.twitch.tv/arseniyshestakov"
  reddit: "https://www.reddit.com/user/SxxxX"
  hackernews: "https://news.ycombinator.com/user?id=SXX"
  deviantart: "https://www.deviantart.com/arseniyshestakov"
  pinterest: "https://www.pinterest.com/arseniyshestakov/"
  artstation: "https://www.artstation.com/arseniyshestakov"
  imdb: "https://www.imdb.com/user/ur65924630/"
  myanimelist: "https://myanimelist.net/profile/arseniyshestakov"

taxonomies:
  category: categories
  tags: tags

Indexes:
  tag: "tags"

permalinks:
  post: /:year/:month/:day/:slug/

MetadataFormat: "yaml"
